# linode galera ansible playbook

# cluster pre-check
- name: pre-check
  hosts: localhost
  user: root
  vars_files:
    - group_vars/galera/vars
  
  roles:
    - precheck

# linodes
- name: configure galera linodes
  hosts: galera_servers
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/galera/vars
  
  roles:
    - common
    - db
    - post


