# roles/firewall/tasks

# set up firewall
- name: install firewalld
  apt:
    name: firewalld
    state: latest

- name: update firewalld.conf
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^IndividualCalls=no'
    line: IndividualCalls=yes

- name: configure firewalld galera service
  template:
    src: firewalld-services-galera.j2
    dest: /etc/firewalld/services/galera.xml
  notify: firewalld enable

- name: configure firewalld internal zone
  template:
    src: firewalld-zones-internal.j2
    dest: /etc/firewalld/zones/internal.xml
  notify: firewalld reload
