# roles/db/handlers
- name: remote firewalld enable
  service:
    name: firewalld
    state: started
    enabled: yes
  run_once: true
  delegate_to: '{{ item }}'
  loop:
    - "{{ groups['galera_servers'][0] }}"
    - "{{ groups['galera_servers'][1] }}"

- name: local firewalld enable
  service:
    name: firewalld
    state: started
    enabled: yes

- name: remote firewalld reload
  shell: firewall-cmd --reload
  run_once: true
  delegate_to: '{{ item }}'
  loop:
    - "{{ groups['galera_servers'][0] }}"
    - "{{ groups['galera_servers'][1] }}"

- name: local firewalld reload
  shell: firewall-cmd --reload
  
  
