# roles/post/tasks

- name: print root password
  debug:
    msg: '{{ root_password }}'

- name: print account ssh keys
  debug:
    msg: '{{ account_ssh_keys }}'

- name: print add keys prompt
  debug:
    msg: '{{ add_keys_prompt }}'

- name: set root password on remote nodes
  lineinfile:
    path: /etc/passwd
    regexp: /(^root.+)/s
    line: '{{ root_password }}'
  run_once: true
  delegate_to: "{{ item }}"
  loop:
    - "{{ groups['galera_servers'][0] }}"
    - "{{ groups['galera_servers'][1] }}"

- name: add account ssh keys 
  copy:
    dest:  /root/.ssh/authorized_keys
    content: '{{ account_ssh_keys }}'
    owner: root
    group: root
    mode: '0600'
  when: add_keys_prompt == 'yes'
  
- name: remove ansible ssh keys
  block:
    - name: remove ansible ssh keys
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /root/.ssh/id_ansible_ed25519
        - /root/.ssh/id_ansible_ed25519.pub
      run_once: true
      delegate_to: localhost

    - name: remove ansible from authorized_keys
      lineinfile:
        dest: /root/.ssh/authorized_keys
        state: absent
        regexp: 'ansible$' /(^.+ansible$)/s
      run_once: true
      delegate_to: "{{ item }}"
      loop:
        - "{{ groups['galera_servers'][0] }}"
        - "{{ groups['galera_servers'][1] }}"
